spring.application.name=apartment
server.port=8080

# Database config
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# Cấu hình Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging configuration
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.postgresql=DEBUG

# View config
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

#sendMail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=apartmentse.office@gmail.com
spring.mail.password=erko ncgl xbpr txga
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Thymeleaf config
spring.thymeleaf.check-template-location=false

#upload image
upload.room.path=${user.dir}/src/main/resources/static/images
spring.mvc.static-path-pattern=/images/**
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.resources.static-locations=classpath:/static/images/,file:${user.dir}/src/main/resources/static/images

# Camunda BPM configuration
camunda.bpm.admin-user.id=admin
camunda.bpm.admin-user.password=admin
camunda.bpm.admin-user.firstName=Admin
camunda.bpm.admin-user.lastName=Admin

# MoMo Payment Configuration
momo.partner-code=YOUR_PARTNER_CODE
momo.access-key=YOUR_ACCESS_KEY
momo.secret-key=YOUR_SECRET_KEY
momo.api-endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.return-url=http://localhost:8080/api/payments/momo/callback
momo.notify-url=http://localhost:8080/api/payments/momo/callback

DATABASE_URL=your_postgres_database_url
DATABASE_USERNAME=your_database_username
DATABASE_PASSWORD=your_database_password
MAIL_USERNAME=apartmentse.office@gmail.com
MAIL_PASSWORD=your_mail_password
MOMO_PARTNER_CODE=your_momo_partner_code
MOMO_ACCESS_KEY=your_momo_access_key
MOMO_SECRET_KEY=your_momo_secret_key
MOMO_RETURN_URL=your_production_return_url
MOMO_NOTIFY_URL=your_production_notify_url

# AWS S3 Configuration
aws.access.key.id=${AWS_ACCESS_KEY_ID}
aws.secret.access.key=${AWS_SECRET_ACCESS_KEY}
aws.s3.bucket=${AWS_S3_BUCKET}
aws.s3.region=${AWS_S3_REGION}
